name: Extract and Deploy Site

on:
  push:
    branches:
      - main  # Sau ramura pe care o folosești pentru a face deploy

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verifică fișierele din repository
      run: |
        ls -alh  # Vei vedea lista fișierelor, inclusiv dacă site.zip este acolo

    - name: Instalează unzip pentru a extrage fișierele .zip
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip

    - name: Extrage fișierele din site.zip
      run: unzip site.zip  # Înlocuiește "site.zip" cu numele fișierului tău .zip

    - name: Mută fișierele extrase în directorul principal
      run: mv site/* ./  # Muta fișierele din folderul "site" în root-ul repository-ului

    - name: Commit și push fișierele extrase
      run: |
        git add .
        git commit -m "Extrase fișiere din site.zip"
        git push origin main  # Asigură-te că faci push la ramura corectă
